### ISSUE TITLE
Auto-generated gen9.js

### ISSUE THREAD

**Issue by AERDU** [pkLucid/Pokemon-Lucid-Calc#1]
Is [gen9](https://github.com/pkLucid/Pokemon-Lucid-Calc/blob/main/js/data/sets/gen9.js) auto-generated in some way? Is there a script that applies the changes made in trainer.party or trainers.h?

**Comment by pkLucid** [comment]
@AERDU sry for the late reply but yes this is auto generated. You can find the script in https://github.com/pkLucid/lucid-calc. Though this uses an older format where both trainer files were split.

**Comment by AERDU** [comment]
I'll give it a try, thanks.

I'll close this and open an issue in [lucid-calc](https://github.com/pkLucid/lucid-calc) if I encounter any issues, if that's OK.
